version: "3"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  api:
    image: api-image
    environment:
      DATABASE_URL: postgres://postgres:password@postgres/database
      PORT: 5000
    depends_on:
      - db
    ports:
      - "5000:5000"
  web:
    image: web-image
    environment:
      API_HOST: api
      PORT: 3000
    depends_on:
      - api
    ports:
      - "3000:3000"
